In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [2]:
x = np.array(
    [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25]
)

copy_x = 1 / (1 + np.exp(-x))
print(copy_x[-5:])

[0.57444252 0.76852478 0.19781611 0.549834   0.47502081 0.52497919
 0.68997448 0.4378235 ]
Last 5:  [0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (x.T).

In [16]:
x = np.array(
    [3,1,4,2,6,1,4,8]
)

y = np.array(
    [5,2,3,12,2,4,17,11]
)

# print(x, y)

# a
print(np.sum(x * y))

# b
print(np.dot(x, y))

# c
print(np.matmul(x, np.transpose(y)))

[3 1 4 2 6 1 4 8] [ 5  2  3 12  2  4 17 11]
Element-wise:  225
Dot:  225
Matmul:  225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [44]:
x = np.array(
    [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2] 
)

o = np.array(
    [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]
)

#print(o[:10])
y = 1 / (1 + np.exp(np.sum(-x * o[:10]) - o[-1:]))

print(y[0])

[ 2.7   0.33 -2.12 -1.73  2.9  -5.8  -0.9  12.11  3.43 -0.5 ]
[0.24176998]


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [17]:
a = np.array(
    [
        [1, 2, 1],
        [3, 0, 1]
    ]
)

b = np.array(
    [
        [0.2],
        [0.3]
    ]
)

x = np.array(
    [[1, 2, 3]]
).transpose()

y = np.matmul(a, x) + b

print(y)

[[8.2]
 [6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [19]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Merge both MovieLens DataFrames into one

In [20]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [78]:
chosen_df = steam_df.loc[(steam_df['behavior-name'] == 'purchase'), 
                         ['user-id', 'value']]
chosen_df = chosen_df.groupby('user-id').sum()
#display(chosen_df.head(10))
print(chosen_df.shape[0])

value
user-id       
5250      21.0
76767     36.0
86540     82.0
103360    10.0
144736     8.0
181212    12.0
229911    27.0
298950   259.0
299153    14.0
381543    10.0

12393

**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [81]:
chosen_df = steam_df.loc[(steam_df['behavior-name'] == 'purchase') & 
                         (steam_df['game-title'] == 'The Elder Scrolls V Skyrim'),
                         ['user-id', 'value']]

print(chosen_df.shape[0])

717

**Task 7.** How many purchases people made on average?

In [116]:
chosen_df = steam_df.loc[(steam_df['behavior-name'] == 'purchase'),
                         ['user-id', 'value']]
chosen_df = chosen_df.groupby('user-id').sum()

people = chosen_df.shape[0]
purchases = chosen_df["value"].sum()

# print(chosen_df['value'].mean())
print(purchases/people)



12393 129511.0
10.45033486645687
10.45033486645687


**Task 8.** Who bought the most games?

In [140]:
chosen_df = steam_df.loc[(steam_df['behavior-name'] == 'purchase'),
                         ['user-id', 'value']]

chosen_df = chosen_df.groupby('user-id').sum()
chosen_df = chosen_df.sort_values(by='value', ascending=False)

#print(chosen_df.head(1))
#print(chosen_df.iloc[0])
print(chosen_df.index[0])

62990992


**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [121]:
chosen_df = steam_df.loc[(steam_df['game-title'] == 'The Elder Scrolls V Skyrim') &
                         (steam_df['behavior-name'] == 'play'),
                        ['game-title', 'value']]

print(chosen_df['value'].mean())

104.71093057607091

game-title  value
1     The Elder Scrolls V Skyrim  273.0
73    The Elder Scrolls V Skyrim   58.0
1066  The Elder Scrolls V Skyrim  110.0
1168  The Elder Scrolls V Skyrim  465.0
1388  The Elder Scrolls V Skyrim  220.0
2065  The Elder Scrolls V Skyrim   35.0
2569  The Elder Scrolls V Skyrim   14.6
3233  The Elder Scrolls V Skyrim  320.0
3363  The Elder Scrolls V Skyrim   80.0
3512  The Elder Scrolls V Skyrim   73.0

**Task 10.** Which games were played the most (in terms of the number of hours played)? Print the first 10 titles and respective numbers of hours.

In [22]:
chosen_df = steam_df.loc[(steam_df['behavior-name'] == 'play'),
                        ['game-title', 'value']]

chosen_df = chosen_df.groupby('game-title').sum().reset_index()
chosen_df = chosen_df.sort_values(by = 'value', ascending=False).reset_index(drop=True)

print(chosen_df.head(10))

game-title     value
0                                       Dota 2  981684.6
1              Counter-Strike Global Offensive  322771.6
2                              Team Fortress 2  173673.3
3                               Counter-Strike  134261.1
4                   Sid Meier's Civilization V   99821.3
5                        Counter-Strike Source   96075.5
6                   The Elder Scrolls V Skyrim   70889.3
7                                  Garry's Mod   49725.3
8  Call of Duty Modern Warfare 2 - Multiplayer   42009.9
9                                Left 4 Dead 2   33596.7

**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print the first 10 titles and respective numbers of hours.

In [31]:
chosen_df = steam_df.loc[(steam_df['behavior-name'] == 'play'),
                        ['user-id', 'game-title', 'value']]

chosen_df = chosen_df.groupby('game-title').agg(
    {
    'user-id':'count',
    'value':'sum'
    }
).reset_index()

#chosen_df['avg-hours-played'] = chosen_df[['user-id', 'value']].apply(lambda x: x[1] / x[0], axis=1)
#chosen_df = chosen_df.sort_values(by = 'avg-hours-played', ascending=False).reset_index(drop=True)

chosen_df['value'] = chosen_df[['user-id', 'value']].apply(lambda x: x[1] / x[0], axis=1)
chosen_df = chosen_df.sort_values(by = 'value', ascending=False).reset_index(drop=True)

print(chosen_df[["game-title", "value"]].head(10))

game-title        value
0            Eastside Hockey Manager  1295.000000
1  Baldur's Gate II Enhanced Edition   475.255556
2                    FIFA Manager 09   411.000000
3                          Perpetuum   400.975000
4              Football Manager 2014   391.984615
5              Football Manager 2012   390.453165
6              Football Manager 2010   375.048571
7              Football Manager 2011   365.703226
8                  Freaking Meatbags   331.000000
9        Out of the Park Baseball 16   330.400000

**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [49]:
df_purchased = steam_df.loc[(steam_df['behavior-name'] == 'purchase'),
                            ['user-id', 'game-title', 'value']]
                           
df_purchased = df_purchased.groupby('game-title').agg(
    {
    'user-id':'count',
    'value':'sum'
    }
)

# display(df_purchased.head(10))

chosen_df = steam_df.loc[:, ['user-id', 'game-title', 'value']]
chosen_df = chosen_df.groupby('game-title').agg(
    {
    'user-id':'count',
    'value':'sum'
    }
)



chosen_df['purchased-count'] = df_purchased['value']
chosen_df['value-minus-purchased'] = chosen_df[['value', 'purchased-count']].apply(
    lambda x: (x[0] - x[1]), axis=1
)

# chosen_df['avg-hours-played'] = chosen_df[['purchased-count', 'value-minus-purchased']].apply(
#     lambda x: (x[1] / x[0]), axis=1
# )
# chosen_df = chosen_df.sort_values(by = 'avg-hours-played', ascending=False)

chosen_df['value'] = chosen_df[['purchased-count', 'value-minus-purchased']].apply(
    lambda x: (x[1] / x[0]), axis=1
)
chosen_df = chosen_df.sort_values(by = 'value', ascending=False).reset_index()

print(chosen_df[["game-title", "value"]].head(10))

                    game-title        value
0      Eastside Hockey Manager  1295.000000
1              FIFA Manager 09   411.000000
2                    Perpetuum   400.975000
3        Football Manager 2012   385.572500
4        Football Manager 2014   382.185000
5        Football Manager 2010   345.439474
6        Football Manager 2011   333.435294
7  Out of the Park Baseball 16   330.400000
8        Football Manager 2013   310.659615
9        Football Manager 2015   307.381013


**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print the first 10 rows from the entire Steam dataset after this change.

In [57]:
def sigmoid_function(value):
    return 1 / (1 + (np.exp(-value / 100)))
        
        

#games_df = steam_df.loc[:, ['user-id', 'game-title', 'behavior-name', 'value', 'zero']]
#games_df['sigmoid-hours-played'] = "-"
#games_df.loc[games_df['behavior-name'] == 'play', 'sigmoid-hours-played'] = sigmoid_function(games_df['value'])

games_df = steam_df.loc[:, ['user-id', 'game-title', 'behavior-name', 'value', 'zero']]
#games_df['sigmoid-hours-played'] = "-"
games_df.loc[games_df['behavior-name'] == 'play', 'value'] = sigmoid_function(games_df['value'])

print(games_df.head(10))


user-id                  game-title behavior-name     value  zero  \
0  151603712  The Elder Scrolls V Skyrim      purchase  1.000000     0   
1  151603712  The Elder Scrolls V Skyrim          play  0.938774     0   
2  151603712                   Fallout 4      purchase  1.000000     0   
3  151603712                   Fallout 4          play  0.704746     0   
4  151603712                       Spore      purchase  1.000000     0   
5  151603712                       Spore          play  0.537181     0   
6  151603712           Fallout New Vegas      purchase  1.000000     0   
7  151603712           Fallout New Vegas          play  0.530213     0   
8  151603712               Left 4 Dead 2      purchase  1.000000     0   
9  151603712               Left 4 Dead 2          play  0.522235     0   

  sigmoid-hours-played  
0                    -  
1                    -  
2                    -  
3                    -  
4                    -  
5                    -  
6                    -  
7                    -  
8                    -  
9                    -

## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [141]:
genres_pop_df = ml_df.loc[:, ['rating', 'genres']]
# display(genres_pop_df.head(10))

genres_pop_df['genres'] = genres_pop_df['genres'].str.split("|") # convert to list
# display(genres_pop_df.head(10))
genres_pop_df = genres_pop_df.explode('genres').reset_index(drop = True) # reset_index to not duplicate indexes
# display(genres_pop_df.head(10))

genres = genres_pop_df.groupby('genres').count()
genres = genres.sort_values(by = "rating", ascending = False).reset_index()

genres.rename({
    'rating': 'n_users'
}, axis = 1, inplace = True)
genres.index.name = "genre"


print(genres)
# display(genres_pop_df.head(10))
# display(ml_df.head(10))

print("""                 genre  n_users
0                Drama    41928
1               Comedy    39053
2               Action    30635
3             Thriller    26452
4            Adventure    24161
5              Romance    18124
6               Sci-Fi    17243
7                Crime    16681
8              Fantasy    11834
9             Children     9208
10             Mystery     7674
11              Horror     7291
12           Animation     6988
13                 War     4859
14                IMAX     4145
15             Musical     4138
16             Western     1930
17         Documentary     1219
18           Film-Noir      870
19  (no genres listed)       47""")


                   genres  n_users
genre                             
0                   Drama    41928
1                  Comedy    39053
2                  Action    30635
3                Thriller    26452
4               Adventure    24161
5                 Romance    18124
6                  Sci-Fi    17243
7                   Crime    16681
8                 Fantasy    11834
9                Children     9208
10                Mystery     7674
11                 Horror     7291
12              Animation     6988
13                    War     4859
14                   IMAX     4145
15                Musical     4138
16                Western     1930
17            Documentary     1219
18              Film-Noir      870
19     (no genres listed)       47
 	                 genre  n_users
0                Drama    41928
1               Comedy    39053
2               Action    30635
3             Thriller    26452
4            Adventure    24161
5              Romance    18124
6   

**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [67]:
genres_pop_df = ml_df.loc[:, ['rating', 'genres']]
# display(genres_pop_df.head(10))

genres_pop_df['genres'] = genres_pop_df['genres'].str.split("|") # convert to list
genres_pop_df = genres_pop_df.explode('genres').reset_index(drop = True) # reset_index to not duplicate indexes

genres = genres_pop_df.groupby('genres').mean()
genres = genres.sort_values(by = "rating", ascending = False).reset_index()

genres.index.name = "genre"


display(genres)
# display(genres_pop_df.head(10))
# display(ml_df.head(10))

print("""                 genre    rating
0            Film-Noir  3.920115
1                  War  3.808294
2          Documentary  3.797785
3                Crime  3.658294
4                Drama  3.656184
5              Mystery  3.632460
6            Animation  3.629937
7                 IMAX  3.618335
8              Western  3.583938
9              Musical  3.563678
10           Adventure  3.508609
11             Romance  3.506511
12            Thriller  3.493706
13             Fantasy  3.491001
14  (no genres listed)  3.489362
15              Sci-Fi  3.455721
16              Action  3.447984
17            Children  3.412956
18              Comedy  3.384721
19              Horror  3.258195""")


genres    rating
genre                              
0               Film-Noir  3.920115
1                     War  3.808294
2             Documentary  3.797785
3                   Crime  3.658294
4                   Drama  3.656184
5                 Mystery  3.632460
6               Animation  3.629937
7                    IMAX  3.618335
8                 Western  3.583938
9                 Musical  3.563678
10              Adventure  3.508609
11                Romance  3.506511
12               Thriller  3.493706
13                Fantasy  3.491001
14     (no genres listed)  3.489362
15                 Sci-Fi  3.455721
16                 Action  3.447984
17               Children  3.412956
18                 Comedy  3.384721
19                 Horror  3.258195

**Task 17.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print first 10 in the form: title, average rating, bias.

In [88]:
df_movies = ml_df[['title', 'rating']]

movies_mean_rating = df_movies['rating'].mean()

df_movies = df_movies.groupby('title').agg({
    'rating': 'mean'
}).reset_index()

df_movies['bias'] = df_movies['rating'] - movies_mean_rating

df_movies.rename({
    df_movies.columns[1]: 'average_rating'
}, axis=1, inplace = True)

print(df_movies.head(10))

title  average_rating      bias
0                               '71 (2014)        4.000000  0.498443
1  'Hellboy': The Seeds of Creation (2004)        4.000000  0.498443
2                   'Round Midnight (1986)        3.500000 -0.001557
3                      'Salem's Lot (2004)        5.000000  1.498443
4                'Til There Was You (1997)        4.000000  0.498443
5          'Tis the Season for Love (2015)        1.500000 -2.001557
6                       'burbs, The (1989)        3.176471 -0.325086
7                     'night Mother (1986)        3.000000 -0.501557
8              (500) Days of Summer (2009)        3.666667  0.165110
9           *batteries not included (1987)        3.285714 -0.215843

**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print first 10 in the form: user_id, average rating, bias.

In [93]:
df_movies = ml_df[['userId', 'rating']]

df_grp_movies = df_movies.groupby(['userId']).agg({
    'rating': 'mean'
}).reset_index()

users_mean_rating = df_movies['rating'].mean()

df_grp_movies['bias'] = df_grp_movies['rating'] - users_mean_rating

df_grp_movies.rename({
    'rating': 'average_rating'
}, axis=1, inplace = True)


print(df_grp_movies.head(10))


         userId  average rating      bias
user-id                                  
0             1        4.366379  0.864822
1             2        3.948276  0.446719
2             3        2.435897 -1.065660
3             4        3.555556  0.053999
4             5        3.636364  0.134807
5             6        3.493631 -0.007926
6             7        3.230263 -0.271294
7             8        3.574468  0.072911
8             9        3.260870 -0.240687
9            10        3.278571 -0.222986


**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task.

In [315]:
# ml_movies_df
# ml_ratings_df
rng = np.random.RandomState(seed=4321)

users = pd.unique(ml_df['userId'])
movies = pd.unique(ml_movies_df['movieId'])

users = sorted(list(rng.choice(users, size=10)))
movies = sorted(list(rng.choice(movies, size=10)))

# display(users)
# display(movies)

movies_df = pd.DataFrame(
    np.array(movies).reshape(-1, 1),
    columns=['movieId']
)
movies_df = movies_df.merge(ml_movies_df, on=['movieId'])

#movie_titles = pd.DataFrame(np.array(movie_ids).reshape(-1, 1), columns=['movieId'])
#movie_titles = movie_titles.merge(ml_movies_df, on=['movieId'])
# display(movies_df)

# users_df = pd.DataFrame(
#     np.array(users),
#     columns=["userId"]
# )

# display(users_df)

users_condition = ml_df['userId'].isin(users)
movies_condition = ml_df['movieId'].isin(movies)

movies_users_df = ml_df.loc[users_condition & movies_condition].copy()
movies_users_df['value'] = 1

# display(movies_users_df.head(10))

inter_matrix = movies_users_df.pivot(
    index="userId",
    columns="title",
    values="value"
#    fill_value=0
)
inter_matrix = inter_matrix.rename_axis(None).rename_axis(None, axis=1)
inter_matrix = inter_matrix.reindex(movies_df['title'].values, axis='columns')
inter_matrix = inter_matrix.reindex(users)
inter_matrix = inter_matrix.fillna(0)

print(inter_matrix)

# display(ml_ratings_df.head(10))
# display(ml_movies_df.head(10))

     Species (1995)  Hairspray (1988)  Big Kahuna, The (2000)  Groove (2000)  \
11              0.0               0.0                     0.0            0.0   
277             0.0               0.0                     0.0            0.0   
286             0.0               0.0                     0.0            0.0   
357             1.0               0.0                     0.0            0.0   
414             1.0               0.0                     1.0            1.0   
428             0.0               0.0                     0.0            0.0   
470             0.0               0.0                     0.0            0.0   
487             0.0               0.0                     0.0            0.0   
543             0.0               0.0                     0.0            0.0   
544             0.0               0.0                     0.0            0.0   

     Open Range (2003)  People Will Talk (1951)  Doctor, The (1991)  \
11                 0.0                      0.0 

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix for the MovieLens dataset. Print the submatrix of first 10 rows and 10 columns.

In [334]:
num_users = ml_df['userId'].max() + 1
num_movies = ml_df['movieId'].max() + 1

inter_mat = np.zeros((num_users, num_movies))

for index, row in ml_df.iterrows():
    user_id = row['userId']
    movie_id = row['movieId']
    inter_mat[user_id][movie_id] = 1

print(inter_mat[:10, :10])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Print the submatrix of first 10 rows and 10 columns.

In [336]:
num_users = ml_df['userId'].max() + 1

inter_mat = np.zeros((num_users, num_movies))

for index, row in ml_df.iterrows():
    user_id = row['userId']
    movie_id = row['movieId']
    inter_mat[user_id][movie_id] = 1

print(inter_mat[:10, :10])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. To prevent hanging your computer because of RAM shortage use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 215.  68.  32.   2.  32.  58.  32.   5.  12.]
 [  0.  68. 110.  26.   3.  22.  36.  18.   6.   3.]
 [  0.  32.  26.  52.   1.  19.  25.  19.   4.   9.]
 [  0.   2.   3.   1.   7.   3.   2.   6.   1.   0.]
 [  0.  32.  22.  19.   3.  49.  24.  23.   4.   9.]
 [  0.  58.  36.  25.   2.  24. 102.  22.   5.   9.]
 [  0.  32.  18.  19.   6.  23.  22.  54.   4.   5.]
 [  0.   5.   6.   4.   1.   4.   5.   4.   8.   0.]
 [  0.  12.   3.   9.   0.   9.   9.   5.   0.  16.]]
